language: php

php:
  - 7.1
  - 7.2

branches:
  only:
    - master
    - development
    - /^feature\/.+$/

before_script:
 - git checkout $TRAVIS_BRANCH
 - composer self-update
 - mkdir -p vendor/bin
 - composer install -o --prefer-dist --no-interaction
 - mkdir build/logs
 - echo "<?php xdebug_set_filter(XDEBUG_FILTER_CODE_COVERAGE, XDEBUG_PATH_WHITELIST, [ '$(pwd)/src' ]);" > .xdebug_filter.php 

script:
 - php -dauto_preprend_file=$(pwd)/.xdebug_filter.php vendor/bin/phpunit.phar -c build/

after_success:
 - travis_retry php vendor/bin/coveralls.phar -v --exclude-no-stmt
